OBJECTS_DIR += $$RELATIVE_PATH/$$OBJ_BUILD_PATH/$$VDEPTH_PATH
DESTDIR = $$RELATIVE_PATH/$$OBJ_BUILD_PATH/$$VDEPTH_PATH
MOC_DIR += $$RELATIVE_PATH/$$OBJ_BUILD_PATH/$$VDEPTH_PATH/moc/release_static
RCC_DIR += $$RELATIVE_PATH/$$OBJ_BUILD_PATH/$$VDEPTH_PATH/rcc/release_static
